# Generated by Django 4.0.3 on 2022-04-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbApp', '0003_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='transfustion_date',
            new_name='transfusion_date',
        ),
    ]
